// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});

// ============================================================
// PARA SUPABASE (PostgreSQL) — use:
// ============================================================
// npx prisma generate --schema=prisma/schema.supabase.prisma
// npx prisma db push --schema=prisma/schema.supabase.prisma
// npx prisma migrate dev --schema=prisma/schema.supabase.prisma
//
// Ou crie prisma.config.supabase.ts:
//
// import "dotenv/config";
// import { defineConfig } from "prisma/config";
//
// export default defineConfig({
//   schema: "prisma/schema.supabase.prisma",
//   migrations: {
//     path: "prisma/migrations.supabase",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
//
// E rode: npx prisma generate --config=prisma.config.supabase.ts
// ============================================================